// // import { Geist, Geist_Mono } from "next/font/google";
// // import "./globals.css";

// // const geistSans = Geist({
// //   variable: "--font-geist-sans",
// //   subsets: ["latin"],
// // });

// // const geistMono = Geist_Mono({
// //   variable: "--font-geist-mono",
// //   subsets: ["latin"],
// // });

// // export const metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// // export default function RootLayout({ children }) {
// //   return (
// //     <html lang="en">
// //       <body
// //         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
// //       >
// //         {children}
// //       </body>
// //     </html>
// //   );
// // }



// import { Inter } from 'next/font/google';
// import { GoogleTagManager } from '@next/third-parties/google'
// import './globals.css';
// import TawkToChat from './TawkToChat'; // 👈 Import your TawkTo component
// import Script from 'next/script';

// const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
//   title: 'Security Support',
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//       <Script async src="https://www.googletagmanager.com/gtag/js?id=G-7TWDE9EQW3"></Script>
// <Script>
//   window.dataLayer = window.dataLayer || [];
//   function gtag(){dataLayer.push(arguments)}
//   gtag('js', new Date());
//   gtag('config', 'G-7TWDE9EQW3');
// </Script>
//         {children}
//         <GoogleTagManager gtmId="G-7TWDE9EQW3"/>
//         <TawkToChat />
//       </body>
//     </html>
//   );
// }


// app/layout.js

import { Inter } from 'next/font/google';
import { GoogleTagManager } from '@next/third-parties/google'
import './globals.css';
import TawkToChat from './TawkToChat'; // 👈 Import your TawkTo component
import Script from 'next/script';

export const metadata = {
  title: 'Your App Title',
  description: 'Your App Description',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* Google Analytics Scripts (Client-side only) */}
        <Script
          strategy="afterInteractive"
           src="https://www.googletagmanager.com/gtag/js?id=G-7TWDE9EQW3"
        />
        <Script
          id="google-analytics"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-7TWDE9EQW3');
            `,
          }}
        />
        {children}
         <GoogleTagManager gtmId="G-7TWDE9EQW3"/>
         <TawkToChat />
      </body>
    </html>
  );
}